// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsxd52vwlfS2vThliQJVpwq3Z53L5tz-A',
    appId: '1:1026131083980:web:baf8b7a8bc4d8dc1d9f869',
    messagingSenderId: '1026131083980',
    projectId: 'carte-aux-tresors-fe1b7',
    authDomain: 'carte-aux-tresors-fe1b7.firebaseapp.com',
    storageBucket: 'carte-aux-tresors-fe1b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5YwXnkkAjXLtM-MsNE-_XKDU5VSIc6Rk',
    appId: '1:1026131083980:android:e4f479351140c856d9f869',
    messagingSenderId: '1026131083980',
    projectId: 'carte-aux-tresors-fe1b7',
    storageBucket: 'carte-aux-tresors-fe1b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABnJ7iTTDPj8JmlloaaTQxWVRskvCpmQY',
    appId: '1:1026131083980:ios:a29da296edf964b4d9f869',
    messagingSenderId: '1026131083980',
    projectId: 'carte-aux-tresors-fe1b7',
    storageBucket: 'carte-aux-tresors-fe1b7.appspot.com',
    iosBundleId: 'com.example.carteAuxTresors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABnJ7iTTDPj8JmlloaaTQxWVRskvCpmQY',
    appId: '1:1026131083980:ios:a29da296edf964b4d9f869',
    messagingSenderId: '1026131083980',
    projectId: 'carte-aux-tresors-fe1b7',
    storageBucket: 'carte-aux-tresors-fe1b7.appspot.com',
    iosBundleId: 'com.example.carteAuxTresors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsxd52vwlfS2vThliQJVpwq3Z53L5tz-A',
    appId: '1:1026131083980:web:c22e4fbefc411f3ad9f869',
    messagingSenderId: '1026131083980',
    projectId: 'carte-aux-tresors-fe1b7',
    authDomain: 'carte-aux-tresors-fe1b7.firebaseapp.com',
    storageBucket: 'carte-aux-tresors-fe1b7.appspot.com',
  );
}
